### ISSUE TITLE
Spaces in group name in groups.tsv break the run

### ISSUE THREAD

**Issue by cnluzon** [elsasserlab/minute#153]
If the group name has a space the run crashes in the `compute_scaling_factors` step. It also crashes if the directory containing the run has spaces in its name, but this seems more like a Snakemake problem. In general, I tend not to use spaces anywhere because they are usually problematic, but I wonder if the tool should be robust to this.

If we are not fixing it, maybe a comment about it in the documentation would be good to have.

**Comment by marcelm** [comment]
If I put a space in the group name, I get this:
```
minute.ParseError: Expected 5 tab-separated fields in groups.tsv, but found 6
```
Spaces have been interpreted as separators in addition to tabs since #135 was merged. I mentioned that allowing this would mean that fields can no longer contain spaces:
https://github.com/NBISweden/minute/issues/134#issuecomment-1015326386

If we allowed only tabs as separators, we could explicitly check whether there’s a space in a field and give nicer error messages. When we allow spaces as separators, we can only give an error like the above.

**Comment by cnluzon** [comment]
Ohh I see, my bad, I was checking on a run from another user on uppmax and I did not realise they ran a version of minute that was not fully updated, so that's probably why I saw this error that was different from the column parsing you mention. I think the nicer error message is good and then I close this issue. Thanks!
